server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: dev-service
          uri: lb://dev-service
          predicates:
            - Path=/dev-service/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**
        - id: manager-service
          uri: lb://manager-service
          predicates:
            - Path=/manager/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**  
